import { useEffect, useState } from "react";
const labels = { operational: "Operational", degraded: "Degraded", down: "Down", unknown: "Not configured" };
export default function App() {
  const [data, setData] = useState(null); const [error, setError] = useState(false);
  useEffect(() => { fetch("/api/status").then((r) => { if (!r.ok) throw new Error(); return r.json(); }).then(setData).catch(() => setError(true)); }, []);
  const overall = data?.overall || "unknown";
  const title = overall === "operational" ? "All systems operational" : overall === "degraded" ? "Some systems are degraded" : overall === "down" ? "System outage detected" : "Status is unavailable";
  return <main className="shell status-shell"><header><a className="brand" href="https://thecaptainexe.me">CAPTAIN<span>.</span></a><nav><a href="https://thecaptainexe.me">Home</a><a href="https://changelog.thecaptainexe.me">Changelog</a><a href="https://labs.thecaptainexe.me">Labs</a><a href="https://downloads.thecaptainexe.me">Downloads</a></nav></header><section className={`status-hero status-${overall}`}><div><p className="eyebrow">Live service health</p><h1>CaptainEXE Status</h1><p className="lead">{title}. Checks run server-side and expose only safe health data.</p></div><div className="overall-orb"><i className={`dot dot-${overall}`} /><strong>{labels[overall]}</strong></div></section>{error && <div className="message">Unable to load this content from our servers.</div>}{!error && !data && <div className="message">Checking systems…</div>}{data && <><div className="status-list">{data.services.map((service) => <div className="status-row" key={service.name}><div><strong>{service.name}</strong><span className="status-latency">{service.latencyMs == null ? "No latency available" : `${service.latencyMs} ms`}</span></div><span className="state"><i className={`dot dot-${service.state}`} />{labels[service.state] || "Unknown"}</span></div>)}</div><p className="meta">Last checked: {new Date(data.checkedAt).toLocaleString()}</p></>}</main>;
}
