import { useEffect, useMemo, useState } from "react";
const genericError = "Unable to load this content from our servers.";
const CDN_ASSET_BASE_URL = "https://cdn.thecaptainexe.me/assets";
const DEFAULT_REPOSITORY_ICON = `${CDN_ASSET_BASE_URL}/github.svg`;
export default function App() {
  const [items, setItems] = useState([]); const [query, setQuery] = useState(""); const [state, setState] = useState("loading");
  useEffect(() => { fetch("/api/changelog").then((response) => { if (!response.ok) throw new Error(); return response.json(); }).then((data) => { setItems(data.entries || []); setState("ready"); }).catch(() => setState("error")); }, []);
  const filtered = useMemo(() => items.filter((item) => `${item.repository} ${item.message} ${item.body} ${item.author}`.toLowerCase().includes(query.toLowerCase())), [items, query]);
  return <main className="shell"><header><a className="brand" href="https://thecaptainexe.me">CAPTAIN<span>.</span></a><nav><a href="https://thecaptainexe.me">Home</a><a href="https://status.thecaptainexe.me">Status</a><a href="https://labs.thecaptainexe.me">Labs</a><a href="https://downloads.thecaptainexe.me">Downloads</a></nav></header><p className="eyebrow">Development feed</p><h1>CaptainEXE Changelog</h1><p className="lead">A chronological record of public development updates across the CaptainEXE ecosystem.</p><div className="toolbar"><input aria-label="Search changelog" placeholder="Search repositories, commits, authors…" value={query} onChange={(event) => setQuery(event.target.value)} /></div>{state === "loading" && <div className="message">Loading changelog…</div>}{state === "error" && <div className="message">{genericError}</div>}{state === "ready" && !items.length && <div className="message">No changelog entries yet.</div>}{state === "ready" && items.length > 0 && !filtered.length && <div className="message">No changelog entries match your search.</div>}<div className="feed">{filtered.map((item) => <a className="card" href={item.url} target="_blank" rel="noreferrer" key={`${item.url}-${item.shortSha || item.version}`}><div className="meta"><img src={item.repositoryIcon?.startsWith(`${CDN_ASSET_BASE_URL}/`) ? item.repositoryIcon : DEFAULT_REPOSITORY_ICON} alt="" /><span>{item.repository}</span><span>·</span><span>{new Date(item.date).toLocaleDateString()}</span><span className="badge">{item.kind}</span></div><h2>{item.message}</h2><p>{item.body}</p><div className="meta">{item.author} · {item.shortSha || item.version}</div></a>)}</div></main>;
}
